name: UPDATE_APP_ACTION

on:
  push:
    branches:
      - master

jobs:
  update-readme-with-appinfo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Secret in Workflow
        run: echo "The API key is ..."
        env:
          REACT_APP_MY_API_KEY: ${{secrets.MY_API_KEY}}